### STAGE 1: Build ###
FROM node:18.16.1-alpine as build
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
COPY . /usr/src/app
RUN npm run build

### STAGE 2: Production Environment ###
FROM nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 3030
CMD ["nginx", "-g", "daemon off;"]